from copy import deepcopy


FIXED_TAXONOMY_VERSION = "fixed-taxonomy-v3"


FIXED_TAXONOMY = {
    "taxonomy_version": FIXED_TAXONOMY_VERSION,
    "model_name": "fixed-taxonomy",
    "model_version": FIXED_TAXONOMY_VERSION,
    "prompt_version": FIXED_TAXONOMY_VERSION,
    "discovery_mode": "fixed",
    "generated_at": None,
    "categories": [
        {
            "name": "Produce",
            "slug": "produce",
            "subcategories": [
                {"name": "Fruits", "slug": "fruits"},
                {"name": "Vegetables", "slug": "vegetables"},
                {"name": "Salad Greens", "slug": "salad-greens"},
                {"name": "Fresh Herbs", "slug": "fresh-herbs"},
                {"name": "Mushrooms", "slug": "mushrooms"},
                {"name": "Cut Fruit & Veg", "slug": "cut-fruit-veg"},
                {"name": "Dried Fruit", "slug": "dried-fruit"},
                {"name": "Nuts & Seeds", "slug": "nuts-seeds"},
                {"name": "Fresh Salsa & Dips", "slug": "fresh-salsa-dips"},
            ],
        },
        {
            "name": "Meat & Seafood",
            "slug": "meat-seafood",
            "subcategories": [
                {"name": "Beef", "slug": "beef"},
                {"name": "Pork", "slug": "pork"},
                {"name": "Chicken", "slug": "chicken"},
                {"name": "Turkey", "slug": "turkey"},
                {"name": "Lamb", "slug": "lamb"},
                {"name": "Sausage", "slug": "sausage"},
                {"name": "Bacon", "slug": "bacon"},
                {"name": "Deli Meats", "slug": "deli-meats"},
                {"name": "Hot Dogs & Franks", "slug": "hot-dogs-franks"},
                {"name": "Seafood", "slug": "seafood"},
                {"name": "Shrimp", "slug": "shrimp"},
                {"name": "Crab & Lobster", "slug": "crab-lobster"},
                {"name": "Fish Fillets", "slug": "fish-fillets"},
                {"name": "Smoked Seafood", "slug": "smoked-seafood"},
                {"name": "Meat Alternatives", "slug": "meat-alternatives"},
            ],
        },
        {
            "name": "Dairy & Eggs",
            "slug": "dairy-eggs",
            "subcategories": [
                {"name": "Milk", "slug": "milk"},
                {"name": "Cream & Creamers", "slug": "cream-creamers"},
                {"name": "Cheese", "slug": "cheese"},
                {"name": "Yogurt", "slug": "yogurt"},
                {"name": "Butter & Margarine", "slug": "butter-margarine"},
                {"name": "Eggs", "slug": "eggs"},
                {"name": "Sour Cream & Cottage Cheese", "slug": "sour-cream-cottage-cheese"},
                {"name": "Dairy Alternatives", "slug": "dairy-alternatives"},
                {"name": "Plant-Based Milk", "slug": "plant-based-milk"},
                {"name": "Plant-Based Yogurt", "slug": "plant-based-yogurt"},
            ],
        },
        {
            "name": "Bakery",
            "slug": "bakery",
            "subcategories": [
                {"name": "Bread", "slug": "bread"},
                {"name": "Bagels & English Muffins", "slug": "bagels-english-muffins"},
                {"name": "Tortillas & Wraps", "slug": "tortillas-wraps"},
                {"name": "Pastries", "slug": "pastries"},
                {"name": "Cakes & Cupcakes", "slug": "cakes-cupcakes"},
                {"name": "Cookies & Brownies", "slug": "cookies-brownies"},
                {"name": "Pies & Tarts", "slug": "pies-tarts"},
                {"name": "Baking Mixes", "slug": "baking-mixes"},
                {"name": "Baking Ingredients", "slug": "baking-ingredients"},
            ],
        },
        {
            "name": "Pantry",
            "slug": "pantry",
            "subcategories": [
                {"name": "Pasta", "slug": "pasta"},
                {"name": "Rice & Grains", "slug": "rice-grains"},
                {"name": "Beans & Legumes", "slug": "beans-legumes"},
                {"name": "Soup & Broth", "slug": "soup-broth"},
                {"name": "Canned Vegetables", "slug": "canned-vegetables"},
                {"name": "Canned Fruit", "slug": "canned-fruit"},
                {"name": "Canned Fish & Meat", "slug": "canned-fish-meat"},
                {"name": "Tomatoes & Tomato Products", "slug": "tomatoes-tomato-products"},
                {"name": "Pasta Sauces", "slug": "pasta-sauces"},
                {"name": "Oils & Vinegars", "slug": "oils-vinegars"},
                {"name": "Spices & Seasonings", "slug": "spices-seasonings"},
                {"name": "Sweeteners", "slug": "sweeteners"},
                {"name": "Nut Butters & Spreads", "slug": "nut-butters-spreads"},
                {"name": "Jams & Honey", "slug": "jams-honey"},
                {"name": "Pickles & Fermented Pantry", "slug": "pickles-fermented-pantry"},
                {"name": "Condiments", "slug": "condiments"},
                {"name": "Salad Dressings", "slug": "salad-dressings"},
                {"name": "Hot Sauce & BBQ Sauce", "slug": "hot-sauce-bbq-sauce"},
                {"name": "Mayo & Mustard", "slug": "mayo-mustard"},
                {"name": "Marinades & Cooking Sauces", "slug": "marinades-cooking-sauces"},
                {"name": "Baking Supplies", "slug": "baking-supplies"},
                {"name": "Flour & Meal", "slug": "flour-meal"},
                {"name": "International Pantry", "slug": "international-pantry"},
                {"name": "Meal Kits & Sides", "slug": "meal-kits-sides"},
            ],
        },
        {
            "name": "Snacks",
            "slug": "snacks",
            "subcategories": [
                {"name": "Chips", "slug": "chips"},
                {"name": "Crackers", "slug": "crackers"},
                {"name": "Cookies", "slug": "cookies"},
                {"name": "Popcorn", "slug": "popcorn"},
                {"name": "Pretzels", "slug": "pretzels"},
                {"name": "Nuts & Trail Mix", "slug": "nuts-trail-mix"},
                {"name": "Fruit Snacks", "slug": "fruit-snacks"},
                {"name": "Candy & Chocolate", "slug": "candy-chocolate"},
                {"name": "Gummies", "slug": "gummies"},
                {"name": "Snack Bars", "slug": "snack-bars"},
                {"name": "Protein Bars", "slug": "protein-bars"},
                {"name": "Jerky & Meat Snacks", "slug": "jerky-meat-snacks"},
                {"name": "Rice Cakes", "slug": "rice-cakes"},
                {"name": "Pita Chips & Dippers", "slug": "pita-chips-dippers"},
                {"name": "Seaweed Snacks", "slug": "seaweed-snacks"},
            ],
        },
        {
            "name": "Beverages",
            "slug": "beverages",
            "subcategories": [
                {"name": "Water", "slug": "water"},
                {"name": "Sparkling Water", "slug": "sparkling-water"},
                {"name": "Juice", "slug": "juice"},
                {"name": "Soda", "slug": "soda"},
                {"name": "Coffee", "slug": "coffee"},
                {"name": "Coffee Beans & Grounds", "slug": "coffee-beans-grounds"},
                {"name": "Coffee Pods & K-Cups", "slug": "coffee-pods-k-cups"},
                {"name": "Coffee Concentrates", "slug": "coffee-concentrates"},
                {"name": "Tea", "slug": "tea"},
                {"name": "Coconut Water", "slug": "coconut-water"},
                {"name": "Kombucha", "slug": "kombucha"},
                {"name": "Sports Drinks", "slug": "sports-drinks"},
                {"name": "Energy Drinks", "slug": "energy-drinks"},
                {"name": "Functional Drinks", "slug": "functional-drinks"},
                {"name": "Drink Mixes", "slug": "drink-mixes"},
                {"name": "Syrups & Mixers", "slug": "syrups-mixers"},
                {"name": "Ready-to-Drink Coffee", "slug": "ready-to-drink-coffee"},
                {"name": "Ready-to-Drink Tea", "slug": "ready-to-drink-tea"},
            ],
        },
        {
            "name": "Alcohol",
            "slug": "alcohol",
            "subcategories": [
                {"name": "Beer", "slug": "beer"},
                {"name": "Wine", "slug": "wine"},
                {"name": "Spirits", "slug": "spirits"},
                {"name": "Hard Seltzer", "slug": "hard-seltzer"},
                {"name": "Cider", "slug": "cider"},
                {"name": "Cocktails & Mixers", "slug": "cocktails-mixers"},
                {"name": "Non-Alcoholic Beer & Wine", "slug": "non-alcoholic-beer-wine"},
            ],
        },
        {
            "name": "Frozen",
            "slug": "frozen",
            "subcategories": [
                {"name": "Frozen Meals", "slug": "frozen-meals"},
                {"name": "Frozen Pizza", "slug": "frozen-pizza"},
                {"name": "Frozen Appetizers", "slug": "frozen-appetizers"},
                {"name": "Frozen Vegetables", "slug": "frozen-vegetables"},
                {"name": "Frozen Fruit", "slug": "frozen-fruit"},
                {"name": "Frozen Meat & Seafood", "slug": "frozen-meat-seafood"},
                {"name": "Frozen Breakfast", "slug": "frozen-breakfast"},
                {"name": "Ice Cream", "slug": "ice-cream"},
                {"name": "Frozen Desserts", "slug": "frozen-desserts"},
                {"name": "Frozen Snacks", "slug": "frozen-snacks"},
            ],
        },
        {
            "name": "Prepared Foods",
            "slug": "prepared-foods",
            "subcategories": [
                {"name": "Prepared Meals", "slug": "prepared-meals"},
                {"name": "Soups & Stews", "slug": "soups-stews"},
                {"name": "Salads & Sides", "slug": "salads-sides"},
                {"name": "Deli Salads", "slug": "deli-salads"},
                {"name": "Sandwiches & Wraps", "slug": "sandwiches-wraps"},
                {"name": "Sushi", "slug": "sushi"},
                {"name": "Kimchi & Banchan", "slug": "kimchi-banchan"},
                {"name": "Dumplings & Quick Meals", "slug": "dumplings-quick-meals"},
                {"name": "Ready-to-Eat Protein", "slug": "ready-to-eat-protein"},
                {"name": "Tofu & Plant-Based Proteins", "slug": "tofu-plant-based-proteins"},
                {"name": "Refrigerated Pasta & Noodles", "slug": "refrigerated-pasta-noodles"},
                {"name": "Refrigerated Desserts", "slug": "refrigerated-desserts"},
            ],
        },
        {
            "name": "International",
            "slug": "international",
            "subcategories": [
                {"name": "Asian Snacks", "slug": "asian-snacks"},
                {"name": "Asian Pantry", "slug": "asian-pantry"},
                {"name": "Asian Noodles & Dumplings", "slug": "asian-noodles-dumplings"},
                {"name": "Hispanic Foods", "slug": "hispanic-foods"},
                {"name": "Italian Foods", "slug": "italian-foods"},
                {"name": "Mediterranean Foods", "slug": "mediterranean-foods"},
                {"name": "Middle Eastern Foods", "slug": "middle-eastern-foods"},
                {"name": "Indian Foods", "slug": "indian-foods"},
                {"name": "Korean Foods", "slug": "korean-foods"},
                {"name": "Japanese Foods", "slug": "japanese-foods"},
                {"name": "Latin American Foods", "slug": "latin-american-foods"},
            ],
        },
        {
            "name": "Supplements & Wellness",
            "slug": "supplements-wellness",
            "subcategories": [
                {"name": "Multivitamins", "slug": "multivitamins"},
                {"name": "Vitamins", "slug": "vitamins"},
                {"name": "Minerals", "slug": "minerals"},
                {"name": "Probiotics", "slug": "probiotics"},
                {"name": "Protein & Collagen", "slug": "protein-collagen"},
                {"name": "Omega & Fish Oil", "slug": "omega-fish-oil"},
                {"name": "Herbal Supplements", "slug": "herbal-supplements"},
                {"name": "Mushroom Supplements", "slug": "mushroom-supplements"},
                {"name": "Sleep Support", "slug": "sleep-support"},
                {"name": "Stress Support", "slug": "stress-support"},
                {"name": "Digestive Support", "slug": "digestive-support"},
                {"name": "Immune Support", "slug": "immune-support"},
                {"name": "Hydration Supplements", "slug": "hydration-supplements"},
                {"name": "Kids Supplements", "slug": "kids-supplements"},
                {"name": "Wellness Shots", "slug": "wellness-shots"},
                {"name": "Essential Oils", "slug": "essential-oils"},
            ],
        },
        {
            "name": "Beauty & Personal Care",
            "slug": "beauty-personal-care",
            "subcategories": [
                {"name": "Skin Care", "slug": "skin-care"},
                {"name": "Hair Care", "slug": "hair-care"},
                {"name": "Body Care", "slug": "body-care"},
                {"name": "Oral Care", "slug": "oral-care"},
                {"name": "Deodorant", "slug": "deodorant"},
                {"name": "Soap & Hand Wash", "slug": "soap-hand-wash"},
                {"name": "Cosmetics", "slug": "cosmetics"},
                {"name": "Sun Care", "slug": "sun-care"},
                {"name": "Lip Care", "slug": "lip-care"},
                {"name": "Feminine Care", "slug": "feminine-care"},
                {"name": "Shaving & Grooming", "slug": "shaving-grooming"},
            ],
        },
        {
            "name": "Household",
            "slug": "household",
            "subcategories": [
                {"name": "Cleaning Supplies", "slug": "cleaning-supplies"},
                {"name": "Dishwashing", "slug": "dishwashing"},
                {"name": "Laundry", "slug": "laundry"},
                {"name": "Paper Products", "slug": "paper-products"},
                {"name": "Trash Bags", "slug": "trash-bags"},
                {"name": "Food Storage", "slug": "food-storage"},
                {"name": "Foil, Wrap & Bags", "slug": "foil-wrap-bags"},
                {"name": "Kitchen Supplies", "slug": "kitchen-supplies"},
                {"name": "Insect Repellent", "slug": "insect-repellent"},
                {"name": "Air Fresheners", "slug": "air-fresheners"},
                {"name": "Home Essentials", "slug": "home-essentials"},
            ],
        },
        {
            "name": "Baby",
            "slug": "baby",
            "subcategories": [
                {"name": "Baby Food", "slug": "baby-food"},
                {"name": "Formula", "slug": "formula"},
                {"name": "Diapers & Wipes", "slug": "diapers-wipes"},
                {"name": "Baby Snacks", "slug": "baby-snacks"},
                {"name": "Baby Care", "slug": "baby-care"},
                {"name": "Baby Wellness", "slug": "baby-wellness"},
            ],
        },
    ],
}


def build_fixed_taxonomy():
    return deepcopy(FIXED_TAXONOMY)
